#!/bin/zsh

main() {
	source zshrc

	ensure_brew
	brew bundle --cleanup
	ensure_ohmyzsh
	ensure_node_lts
	ensure_rust_tooling
	ensure_tms
	symlink
}

ensure_tms() {
	ensure "tmux-sessionizer"

	tms config -p ~/Desktop
}

ensure_rust_tooling() {
	ensure "Rust Tooling"
	rustup toolchain install stable
	cargo install cargo-watch
}

ensure_node_lts() {
	ensure "Node LTS"
	nvm install --lts
}

ensure_ohmyzsh() {
	ensure "Oh-My-ZSH"
	command -v omz >/dev/null || \
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
}

ensure_brew() {
	ensure "Homebrew"
	command -v brew >/dev/null || \
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

symlink() {
	echo ""
	echo ">>> Ensuring Symlinks."

	ln -f $(pwd)/zshrc          $HOME/.zshrc
	ln -f $(pwd)/gitconfig      $HOME/.gitconfig
	ln -f $(pwd)/tmux.conf      $HOME/.tmux.conf
  ln -f $(pwd)/alacritty.toml $HOME/.alacritty.toml

	mkdir -p $HOME/.config
	[ ! -e $HOME/.bin ]         && ln -sf $(pwd)/bin $HOME/.bin
	[ ! -e $HOME/.config/nvim ] && ln -sf $(pwd)/nvim $HOME/.config/nvim
}

ensure() {
	echo ""
	echo ">>> Ensuring $1."
}

main
