#!/bin/zsh

main() {
	source zshrc

	ensure_brew
	brew bundle --cleanup

	ensure_ohmyzsh

	symlink
}

ensure_ohmyzsh() {
	command -v omz >/dev/null || \
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
}

ensure_brew() {
	command -v brew >/dev/null || \
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

symlink() {
	ln -f $(pwd)/zshrc     $HOME/.zshrc
	ln -f $(pwd)/gitconfig $HOME/.gitconfig
}

main
