#!/bin/zsh

main() {
	source zshrc

	ensure_brew
	brew bundle --cleanup
	ensure_ohmyzsh
	ensure_node_lts
	ensure_tms
	symlink

	helix_health
}

helix_health() {
	ensure "Helix Health"

	# Table Header
	# Languages...
	hx --health | grep \
		-e '^Language.*LSP.*DAP.*Formatter.*Highlight.*Textobject.*Indent' \
		-e '^typescript' \
		-e '^zig' \
		-e '^prisma'
}

ensure_tms() {
	ensure "tmux-sessionizer"

	tms config -p ~/Desktop
}

ensure_node_lts() {
	ensure "Node LTS"
	nvm install --lts
	npm install -g @prisma/language-server
}

ensure_ohmyzsh() {
	ensure "Oh-My-ZSH"
	command -v omz >/dev/null || \
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
}

ensure_brew() {
	ensure "Homebrew"
	command -v brew >/dev/null || \
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

symlink() {
	echo ""
	echo ">>> Ensuring Symlinks."

	ln -sf $(pwd)/zshrc          $HOME/.zshrc
	ln -sf $(pwd)/gitconfig      $HOME/.gitconfig
	ln -sf $(pwd)/tmux.conf      $HOME/.tmux.conf
  ln -sf $(pwd)/alacritty.toml $HOME/.alacritty.toml
  ln -sf $(pwd)/jjconfig.toml  $HOME/.jjconfig.toml

	mkdir -p $HOME/.config
	[ ! -e $HOME/.bin ]          && ln -sf $(pwd)/bin   $HOME/.bin
	[ ! -e $HOME/.config/nvim ]  && ln -sf $(pwd)/nvim  $HOME/.config/nvim
	[ ! -e $HOME/.config/helix ] && ln -sf $(pwd)/helix $HOME/.config/helix
}

ensure() {
	echo ""
	echo ">>> Ensuring $1."
}

main
